---
- hosts: all
  become: yes
  tasks:
    - name: Check for Python
      raw: test -e /usr/bin/python
      changed_when: false
      failed_when: false
      register: check_python

    # - name: Install Python
    #   raw: yum -y install python
    #   when: check_python.rc != 0
    - name: Print message
      debug:
        msg: "{{ check_python.rc }}"

    - name: Install Nginx
      apt:
        name: nginx
        state: latest

    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: Creates directory
      file:
        path: /home/ubuntu/files
        state: directory
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
